// Generated by rta app sync. Do not edit.
export const webOperations = [
  "main.advance",
  "main.check-status",
  "main.frame",
  "main.operate",
  "main.pause",
  "main.play",
  "main.set-speed",
  "main.set-text",
  "main.status",
  "main.stop"
] as const;
export type WebOperationId = typeof webOperations[number];
